In [1]:
import numpy as np

In [5]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a[0],a[2],a[-1]  # indice begins always at 0

(0, 2, 9)

In [13]:
a[::-1]  # start from begin to end step -1 == reverse

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [10]:
a = np.diag(np.arange(3))
a[1]

array([0, 1, 0])

In [12]:
a = np.arange(10)
a[1:3]

array([1, 2])

In [32]:
a = np.arange(36)
a.shape

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [31]:
a=a.reshape((6,6),order='F')
a[2::2,::2]

array([[ 2, 14, 26],
       [ 4, 16, 28]])

In [36]:
a=a.reshape((6,6),order='F')
a

array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

In [38]:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [40]:
b = np.arange(5)
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [41]:
np.arange(6)+np.arange(0,51,10)

array([ 0, 11, 22, 33, 44, 55])

In [42]:
np.arange(6)+np.arange(0,51,10)[:,np.newaxis]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])