In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [5]:
2**a

array([ 2,  4,  8, 16])

In [11]:
b = np.ones(4) + 1
a - b
a * b
j = np.arange(5)
2**(j+1)-j

array([ 2,  3,  6, 13, 28])

In [14]:
a = np.arange(10000)
%timeit a + 1

The slowest run took 6.70 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 7.76 µs per loop


In [15]:
l = range(10000)
%timeit [i+1 for i in l]

1000 loops, best of 3: 590 µs per loop


In [16]:
c = np.ones((3,3)) # product of elements
c * c

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [17]:
c.dot(c) # matrix multiplication

array([[ 3.,  3.,  3.],
       [ 3.,  3.,  3.],
       [ 3.,  3.,  3.]])

In [5]:
help(np.tril)  ## Lower triangle
help(np.triu)  ## Upper triangle

Help on function tril in module numpy.lib.twodim_base:

tril(m, k=0)
    Lower triangle of an array.
    
    Return a copy of an array with elements above the `k`-th diagonal zeroed.
    
    Parameters
    ----------
    m : array_like, shape (M, N)
        Input array.
    k : int, optional
        Diagonal above which to zero elements.  `k = 0` (the default) is the
        main diagonal, `k < 0` is below it and `k > 0` is above.
    
    Returns
    -------
    tril : ndarray, shape (M, N)
        Lower triangle of `m`, of same shape and data-type as `m`.
    
    See Also
    --------
    triu : same thing, only for the upper triangle
    
    Examples
    --------
    >>> np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
    array([[ 0,  0,  0],
           [ 4,  0,  0],
           [ 7,  8,  0],
           [10, 11, 12]])



In [14]:
a = np.triu(np.ones((3,3)),1)
a += a.T
a

array([[ 0.,  1.,  1.],
       [ 1.,  0.,  1.],
       [ 1.,  1.,  0.]])

In [16]:
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [17]:
x.sum(axis=0)  # basic reductions

array([3, 3])

In [18]:
x.sum(axis=1)

array([2, 4])